[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/crm/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
